### PR TITLE
Add support search by query

### PR DESCRIPTION
**Pull request by andtsarenko**

### CODE REVIEW

**Comment by ewnd9** [comment]
It's a viable solution if you only add `query.query` without removing the `imdbId` variable. One important thing is to use the private method  `api._search({ query: 'How I meet your mother' }, () => true)` instead of `api.search({ query: 'How I meet your mother' })`

**Comment by HoldenCa** [comment]
But if I will have not deleted 

> const imdbId = query.imdbid.replace('tt', '');

I still must supply imdbId property to query otherwise exception will be thrown.
But I wonder why search query object is so tight with this property?

**Comment by HoldenCa** [comment]
I think that if you need search method designed for searching by imdbdid it's better to create method searchByImdbId(qery) but leave _serach() method pure.

**Comment by ewnd9** [comment]
> I still must supply imdbId property to query otherwise exception will be thrown.

You are right, I didn't take it into account.

> But I wonder why search query object is so tight with this property?

This simply is my use case, I've always used opensubtitles in conjunction with other APIs for searching imdb / fetch posters, so imdb is the only param 

---

I added query support in https://github.com/ewnd9/opensubtitles-universal-api/commit/40edf736e078a82d8529f5cb4c2d5f5ba0612390 and released `v1.2.0`, let me know if it is working for you.

**Comment by andtsarenko** [comment]
Thanks for you effort. At first glance everything is ok.

**Pull request closed without merging**
